[project]
name = "kt-ai-academy-202510"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-ai-inference>=1.0.0b9",
    "faiss-cpu>=1.12.0",
    "graph-rag-example-helpers>=0.8.0",
    "ipykernel>=7.0.1",
    "langchain-community>=0.3.31",
    "langchain-graph-retriever>=0.8.0",
    "langchain-openai>=0.3.35",
    "langgraph>=1.0.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "pydantic>=2.12.2",
    "pymupdf>=1.26.5",
    "python-dotenv>=1.1.1",
    "ragas>=0.3.7",
    "rouge-score>=0.1.2",
    "sacrebleu>=2.5.1",
    "scikit-learn>=1.7.2",
]
